### ISSUE TITLE
Request for ideas

### ISSUE THREAD

**Issue by jd-campbell** [soybase/jekyll-soybase#102]
I want to start thinking about blog ideas for the Jekyll-SB.  I have started documenting my ideas in the [Stakeholder_involvement repo](https://github.com/soybase/Stakeholder_involvement).  I want to ask you for your assistance to think of new ideas and / or help me with some of ideas I have written down below.

What I have currently for ideas:
- History of SoyBase
     *- Interview Randy and David*
- Breeding history of Williams82
    **- Who do I need to talk to for this?**
- Bredding history of Lee
    **- Who do I need to talk to for this?**
- Highlist a scientist/breeders?
    *- Past SoyGEC winners, Past SBW poster winners*
- Quarter or yearly SoyBase update
    *- New tools and new data*

**Comment by maxglycine** [comment]
Lee registered in 1958 this has a brief history https://acsess.onlinelibrary.wiley.com/doi/epdf/10.2134/agronj1958.00021962005000110016x

There is no "Past" SoyGEC winners, only Current. Contact the people on the SoyGEC page directly

I do not know if the poster winners were recorded in past SBWs. I will ask the Committee for names and emails for this year.

History of SoyBase.  I will email David and ask him to write up a short history

Breeding history of Williams 82.  Registered in 1988.  Registration notice is here https://acsess.onlinelibrary.wiley.com/doi/10.2135/cropsci1988.0011183X002800060049x
@jd-campbell
