### ISSUE TITLE
Excessive number of branches??

### ISSUE THREAD

**Issue by maxglycine** [soybase/jekyll-soybase#104]
I was looking at the branches listed for main and there a lot of them.  Are they all open?  If not should some be removed from the list? @nathanweeks @StevenCannon-USDA @jd-campbell @weihuang12

**Comment by StevenCannon-USDA** [comment]
Thanks; I have reviewed and deleted some this morning. I left those for which I was unsure of the status. If you recognize any others that are abandoned or sufficiently stale, it would be good to delete them.
