### ISSUE TITLE
Improve gene-name lookup/correspondence page

### ISSUE THREAD

**Issue by StevenCannon-USDA** [soybase/jekyll-soybase#112]
Provide ways for users to 

1. Easily look up corresponding genes for a given gene ID
2. Look up corresponding genes for a given list of gene IDs

The page to be improved is: https://dev.soybase.org/tools/translate/

Self-assigning @StevenCannon-USDA for several easier fixes/updates. Handling the list of supplied gene IDs is a larger project, probably to be implemented as a new web component -- which needs to be specified.

**Comment by jd-campbell** [comment]
@StevenCannon-USDA  I am going to close this issue.
