### ISSUE TITLE
BrAPI Pedigree Viewer

### ISSUE THREAD

**Issue by jd-campbell** [soybase/jekyll-soybase#120]
Request to look into [BrAPI Pedigree Viewer](https://github.com/solgenomics/BrAPI-Pedigree-Viewer) for the SoyBase parentage data. 

Current SoyBase parentage webpage is located [here](https://dev.soybase.org/tools/parentage/). 

A few things to consider:

1. What are the pedigree viewer dependencies?
2. What is the file format required for the viewer?
3. Can the pedigree be drawn quickly for the user or does a pedigree diagram need to be drawn and saved for users?
4. The example BrAPI viewer has a user name and password. Is the username and passwd required?

**Comment by maxglycine** [comment]
It appears we will have to have a germplasm BRAPI compliant end point.  That is what the pedigree viewer uses.  It seems that a service could be made that utilizes a text file or a MySQL DB.  If a text file is used there would be some lag reading it into a hash.  We would have to distinguish not only parent child relationships but also "siblings".  I don't have a sibling relationship in the database.  You can identify those through the comments field.  I usually put "reselection" to denote a sibling.  We would probably want to change the table to include a "sibling" field.  This would have to be reflexive of course. @jd-campbell @StevenCannon-USDA
