### ISSUE TITLE
New homepage overflows on mobile

### ISSUE THREAD

**Issue by That-Thing** [soybase/jekyll-soybase#129]
The new changes to the homepage overflow horizontally when the screen size is reduced.
![image](https://github.com/soybase/jekyll-soybase/assets/41160238/60bd8e90-e968-412a-8078-f1e15f096d45)

**Comment by StevenCannon-USDA** [comment]
Thanks for checking and reporting, Simon.
Would you be willing to take over in this page? I expect a lot of changes should be made: maybe move some repeated stuff into common CSS for the page if possible; make the buttons reactive; etc.

It will probably be best for you to work from the new branch `may-cleanup`, where I have fixed a link in the alerts.html and made a few more cosmetic changes to the home page (which you're free to experiment with and change).

Also, an important fix in the datastore-metadata, which affected the tools/browsers content. To get these changes, do:
`git submodule update --recursive`

**Comment by That-Thing** [comment]
Will do. 
I've also noticed some minor styling issues with the table which I will also fix.

**Comment by That-Thing** [comment]
The overflow issue is fixed, but not perfectly. I will work on getting the table to display nicer on mobile.

**Comment by StevenCannon-USDA** [comment]
Addressed in https://github.com/soybase/jekyll-soybase/pull/131 (I believe). At least: the button section is scrollable on mobile. Closing.
