### ISSUE TITLE
Static page: about/data_repositories/

### ISSUE THREAD

**Issue by jd-campbell** [soybase/jekyll-soybase#13]
On the top of the page it says "XX Say something about why it is important to deposit research data in a DOI-conferring repos" 

Needs to be completed to be marked as done.

**Comment by StevenCannon-USDA** [comment]
Completed in 2023-09-07 scannon feature branch. Will review and merge at SoyBase-Jekyll/GitHub meeting.

**Comment by jd-campbell** [comment]
Fixed and merged into main
