### ISSUE TITLE
Refactor browsers code and sort by genotype within strain.accession_group

### ISSUE THREAD

**Issue by StevenCannon-USDA** [soybase/jekyll-soybase#130]
The liquid code in tools/browsers/index.html is pretty convoluted. Consider writing a separate script that produces a `_data/FILE.yml` that is can be parsed/traversed with simpler liquid code. 

This scripted code could be a modification/extension of LIS autocontent?

Also, it would be good to sort the genotypes under the first-displayed strain.accession_group (for some reason, the sorting seems to be funky only for "Reference - Williams 82".
<img width="324" alt="Screenshot 2024-05-15 at 1 41 43 PM" src="https://github.com/soybase/jekyll-soybase/assets/3588740/c180f236-155d-4f4b-bde7-dbc3d8519512">

**Comment by jd-campbell** [comment]
@StevenCannon-USDA  Can this issue be closed?

**Comment by StevenCannon-USDA** [comment]
> @StevenCannon-USDA Can this issue be closed?

Yes. This was fixed with https://github.com/soybase/jekyll-soybase/pull/137.

Closing.
