### ISSUE TITLE
Static Page: /about/lgs_and_chromosomes/

### ISSUE THREAD

**Issue by jd-campbell** [soybase/jekyll-soybase#14]
The table needs to have a boarder around each cell so that it is easier to read.  Is this a ui-toolkit issue?

**Comment by That-Thing** [comment]
UIkit doesn't have a border that can be added, but some simple CSS should do the trick.

Would something like this work?
![image](https://github.com/soybase/jekyll-soybase/assets/41160238/5ae80cad-6af7-40b7-a1b7-4a3509a605bb)

**Comment by maxglycine** [comment]
Yes, looks great

Thanks

Rex Nelson

***@***.***

On Aug 28, 2023, at 5:51 PM, Simon ***@***.***> wrote:

﻿

UIkit doesn't have a border that can be added, but some simple CSS should do the trick.

Would something like this work?
[image]<https://user-images.githubusercontent.com/41160238/263853751-5ae80cad-6af7-40b7-a1b7-4a3509a605bb.png>

**Comment by maxglycine** [comment]
Yes, looks great.

Thanks

Rex Nelson

***@***.***

On Aug 28, 2023, at 5:51 PM, Simon ***@***.***> wrote:

﻿

UIkit doesn't have a border that can be added, but some simple CSS should do the trick.

Would something like this work?
[image]<https://user-images.githubusercontent.com/41160238/263853751-5ae80cad-6af7-40b7-a1b7-4a3509a605bb.png>

**Comment by maxglycine** [comment]
Since you have room, spell out "Length(cM)"

**Comment by That-Thing** [comment]
Would rewriting the markdown table format into HTML be ok? 

Markdown doesn't allow for a class to be added to the table element.

**Comment by StevenCannon-USDA** [comment]
> Would rewriting the markdown table format into HTML be ok?
> 
> Markdown doesn't allow for a class to be added to the table element.

I am not sure about implications of implementation options, but generally we're looking for some combination of elegance, maintainability, and function/attractiveness in the rendered html. I would think a decent compromise for this case would be to store the data as a plain TSV table (in _data), and iterate over that to generate the html.
https://idratherbewriting.com/documentation-theme-jekyll/mydoc_tables.html

**Comment by That-Thing** [comment]
Storing everything in _data would certainly make things a lot neater.

Should I implement this?

**Comment by StevenCannon-USDA** [comment]
@That-Thing - That would be great.
For tidiness, it would probably be good to put the data in a subdirectory - maybe
_data/about/chr_correspondences.tsv

**Comment by That-Thing** [comment]
I have found that creating an about directory in _data causes issues with the already existing data.yml, renaming the about directory to something else would solve this issue.

**Comment by StevenCannon-USDA** [comment]
OK. No real need for the subdirectory I guess. Let's just go with _data/chr_correspondences.tsv then.

**Comment by That-Thing** [comment]
Pushed changes to [new branch](https://github.com/soybase/jekyll-soybase/tree/chr_correspondences)

**Comment by maxglycine** [comment]
There is no advantage to using liquid to render text that does not change. It is obviously restricting what style that can be applied in this case. We will use html in this case.
