### ISSUE TITLE
nitpicky DS request

### ISSUE THREAD

**Issue by jd-campbell** [soybase/jekyll-soybase#148]
This is a very 'nitpicky' request ..... Is there any way to change the icon on the top left corner of the https://data.soybase.org/Glycine/ ? 

Because it says Glycine but the LegumeInfo Icon is there. 
![Screenshot 2024-08-15 at 15 31 28](https://github.com/user-attachments/assets/4befef98-991d-4991-a99b-d7b00a011381)

If it not possible that is fine. 

If it is possible here is a copy if the SoyBase logo. 
![sb_logo_alone_lft_bright1](https://github.com/user-attachments/assets/6f0c4989-4632-49db-8806-f0eee16994fd)

**Comment by ChenProm-USDA** [comment]
Made changes to https://github.com/legumeinfo/h5ai/tree/data.legumeinfo.org. 
Wrote logic to render logo based on the page url.  Logo is being pull from https://dev.soybase.org/assets/img/sb_logo.png.

Creating a release.

**Comment by ChenProm-USDA** [comment]
Fix pushed to production.
