### ISSUE TITLE
Static page: /about/soybase_project.php

### ISSUE THREAD

**Issue by jd-campbell** [soybase/jekyll-soybase#15]
This static page is marked as done in the previous project page but @jd-campbell could not find it. 
@maxglycine do you have this page on your computer?

**Comment by maxglycine** [comment]
No, I believe that @StevenCannon-USDA  did it

**Comment by StevenCannon-USDA** [comment]
If you're referring to a staff page - I am not aware that this been done, though there is a (currently unlinked) page giving SoyBase history:
https://dev.soybase.org/about/soybase_about/

A reference to this needs to be added to _data/about.yml

A staff page would probably be in a new directory, e.g. https://dev.soybase.org/about/soybase_staff
and a corresponding data file in _data
I see that images have already been added here: assets/img/team/

These could all be easy little introductory tasks for someone new to Jekyll.

**Comment by StevenCannon-USDA** [comment]
Marking this as done (in 2023-09-07 scannon branch). The page was there; it just needed to be linked from about/index.php (via _data/about.yml).

**Comment by maxglycine** [comment]
I am confused. Has this been done in the scannon branch and not pulled into main.  I don't see it on Dev.soybase.org.  Or is it to be done through modification of _data/about.yml?

**Comment by StevenCannon-USDA** [comment]
@maxglycine -- sorry - it's still languishing in my branch.
I've been mired in pan-gene and gene family work over the last week.
Next-up: updating the specs, and then I'll finish my branch. ETA Tuesday sometime.

**Comment by StevenCannon-USDA** [comment]
I think this is done. @maxglycine made the changes on the page itself (/about/soybase_about/), and I added a link from /about/
