### ISSUE TITLE
Events box on homepage

### ISSUE THREAD

**Issue by jd-campbell** [soybase/jekyll-soybase#158]
@ChenProm-USDA 

I am requesting your help with something small (or at least I hope it is small).  I am working on the branch named [add-meetings-09-11-24](https://github.com/soybase/jekyll-soybase/tree/add-meetings-09-11-24) and I am trying to get the date after the hyperlink to be on the next line. 

Currently the date and link on the same line. see screen shot
![Screenshot 2024-09-11 at 13 39 35](https://github.com/user-attachments/assets/e0147d80-af6f-4568-b46d-1d45ec6115a4)

What I would prefer and I think easier to read is having the date right under (or the next line) after the link. see screen shot: 
![Screenshot 2024-09-11 at 13 40 13](https://github.com/user-attachments/assets/a0b27c37-6386-4208-a095-91ba6b991b06)

**Comment by ChenProm-USDA** [comment]
Layout is controlled by _theme/jekyll-theme-legumeinfo/_includes/card-items.html.  
To fix:
Make a copy of this component in the root _includes folder and update with code below.

```
<li>
    <a href="{{ include.url }}"><b>{{ include.title }}</b></a>
    {% if include.meta %} <div>{{ include.meta }}</div>{% endif %}
</li>

**Comment by ChenProm-USDA** [comment]
@jd-campbell  I pushed some changes to the branch please pull down and review.
