### ISSUE TITLE
Merge #160 failed; Can't merge #161

### ISSUE THREAD

**Issue by jd-campbell** [soybase/jekyll-soybase#162]
Nathan, 

Chen brought to my attention that my [PR #160 (https://github.com/soybase/jekyll-soybase/pull/160). I remember that there are a few check-links that would fail. But some some reason by pa11y also failed. 

Also I am noticed that [PR #161](https://github.com/soybase/jekyll-soybase/pull/161) has been approved by me, however the Squash and Merge button is grayed out.

**Comment by nathanweeks** [comment]
Re 160: known issue -- pa11y checks had never passed 
Re 161: try clicking on the Squash and Merge button. I think the button not being green is a (new?) visual cue that some checks failed, but the PR looks mergeable.
