### ISSUE TITLE
Labels for Keyword search, Gene identifier search, and Synteny viewer don't point to input 

### ISSUE THREAD

**Issue by That-Thing** [soybase/jekyll-soybase#171]
Labels for search inputs don't include a "for" attribute on the homepage.
Ex: 
`<label class="uk-text-bold">Keyword Search</label>` should be `<label class="uk-text-bold for="quickSearchInput">Keyword Search</label>`

**Comment by StevenCannon-USDA** [comment]
Closing; fixed in commit b20b816
