### ISSUE TITLE
Static Page: /tools/ontology/

### ISSUE THREAD

**Issue by jd-campbell** [soybase/jekyll-soybase#19]

**Comment by jd-campbell** [comment]
@jd-campbell @maxglycine 

Using Jekyll to generate this html/php page : https://soybase.org/ontology.php

- Keep all the current words and links that are within the text
- Keep buttons with current words
- Links for the buttons should go to new Amigo URL @nathanweeks needs to provide
- Free to organize or redesign

**Comment by nathanweeks** [comment]
> * Links for the buttons should go to new Amigo URL @nathanweeks needs to provide

https://amigo.soybase.org/amigo/amigo

**Comment by jd-campbell** [comment]
@Cheehau0659 
We also have this issue / Static page for you to work on. Remember classes/study come first.
