### ISSUE TITLE
Fix broken links (Focus on code 404)

### ISSUE THREAD

**Issue by jd-campbell** [soybase/jekyll-soybase#26]
For the Links > External check, the following failures were found:

- [x]  At ./about/soybase_about/index.html:606:

  External link https://www.ers.usda.gov/media/1736347/ocs_[15](https://github.com/soybase/jekyll-soybase/actions/runs/6039822999/job/16389397153#step:7:16)a.pdf failed (status code 404)

- [x]  At ./about/soybase_about/index.html:606:

  External link https://usda.mannlib.cornell.edu/usda/ers/AES//2010s/2013/AES-12-02-2013.pdf failed (status code 404)

- [x]  At ./about/soybase_about/index.html:606:

  External link https://www.nass.usda.gov/Charts_and_Maps/Crops_County/pdf/SB-HA13-RGBChor.pdf failed (status code 404)

- [x]  At ./about/soybase_about/index.html:606:

  External link https://www.usda.gov/nass/PUBS/TODAYRPT/cropan15.pdf failed (status code 404)

- [x]  At ./about/soybase_about/index.html:606:

  External link https://www.usda.gov/nass/PUBS/TODAYRPT/cropan15.pdf failed (status code 404)

- [x]  At ./about/soybase_about/index.html:606:

  External link https://soymeal.org/FactSheets/OmnivorousFwFishTechReview.pdf failed (status code 404)

(403)* At ./events/2023/06/18/WSRC11.html:509:

  External link https://www.wsrc11vienna.com failed (status code 403)

- [x]   At ./news/general/2022/07/18/new-SoyBase-site.html:524:

  External link https://legacy.legumeinfo.org failed: got a time out (response code 0) (status code 0)

(403)* At ./projects/bayer_valliyodan_2021/index.html:521:

  External link https://doi.org/10.1002/tpg2.20109 failed (status code 403)

- [x]   At ./projects/bhattacharyya_2018/index.html:521:

  External link https://doi.org/XX failed (status code 404)

* At ./projects/lee_jeong_2015/index.html:521:

  External link https://doi.org/10.1111/tpj.12755 failed (status code 403)

- [x]   At ./projects/milestonereseq_20[16](https://github.com/soybase/jekyll-soybase/actions/runs/6039822999/job/16389397153#step:7:17)/index.html:521:

  External link https://doi.org/XX failed (status code 404)

* At ./projects/soynam_2014/index.html:553:

  External link https://doi.org/10.3835/plantgenome2016.10.0109 failed (status code 403)

* At ./projects/soynam_2014/index.html:609:

  External link https://doi.org/10.2135/cropsci2018.09.0573 failed (status code 403)

- [x]  At ./projects/soynam_2014/index.html:636:

  External link https://soybase.org/data/v2/Glycine/max/diversity/Wm82.gnm1.div.Bandillo_Lorenz_20[17](https://github.com/soybase/jekyll-soybase/actions/runs/6039822999/job/16389397153#step:7:18)/glyma.Wm82.gnm1.div.Bandillo_Lorenz_2017.SNPs.parents.vcf.gz failed: Not Found (status code 404)

- [x]   At ./projects/soynam_2014/index.html:640:

  External link https://soybase.org/data/v2/Glycine/max/diversity/Wm82.gnm2.div.Bandillo_Lorenz_2017/glyma.Wm82.gnm2.div.Bandillo_Lorenz_2017.SNPdata.parents.vcf.gz failed: Not Found (status code 404)

- [x]  At ./projects/soynam_2014/index.html:644:

  External link https://soybase.org/data/v2/Glycine/max/diversity/Wm82.gnm1.div.Bandillo_Lorenz_2017/glyma.Wm82.gnm1.div.Bandillo_Lorenz_2017.SNPs.parents-progeny.vcf.gz failed: Not Found (status code 404)

- [x]  At ./projects/soynam_2014/index.html:648:

  External link https://soybase.org/data/v2/Glycine/max/diversity/Wm82.gnm2.div.Bandillo_Lorenz_2017/glyma.Wm82.gnm2.div.Bandillo_Lorenz_2017.SNPdata.parents-progeny.vcf.gz failed: Not Found (status code 404)

- [x]  At ./projects/soynam_2014/index.html:652:

  External link https://soybase.org/data/v2/Glycine/max/diversity/Wm82.gnm2.div.Song_NAM_2021 failed: Not Found (status code 404)

* At ./projects/torkamaneh_laroche_2021/index.html:521:

  External link https://doi.org/10.1111/pbi.13466 failed (status code 403)

* At ./projects/torkamaneh_laroche_2021/index.html:535:

  External link https://doi.org/10.3835/plantgenome20[18](https://github.com/soybase/jekyll-soybase/actions/runs/6039822999/job/16389397153#step:7:19).08.0061 failed (status code 403)

* At ./projects/torkamaneh_lemay_2019/index.html:521:

  External link https://doi.org/10.1111/pbi.13600 failed (status code 403)

* At ./projects/valliyodan_cannon_2016/index.html:521:

  External link https://doi.org/10.1111/tpj.14500 failed (status code 403)

* At ./resources/index.html:918:

  External link https://doi.org/10.1111/tpj.14500 failed (status code 403)

* At ./resources/index.html:1[19](https://github.com/soybase/jekyll-soybase/actions/runs/6039822999/job/16389397153#step:7:20)3:

  External link https://doi.org/10.1111/tpj.14500 failed (status code 403)

* At ./tools/browsers/index.html:9[22](https://github.com/soybase/jekyll-soybase/actions/runs/6039822999/job/16389397153#step:7:23):

  External link https://doi.org/10.1111/tpj.14500 failed (status code 403)

- [x]   At ./tools/browsers/index.html:1034:

  External link https://doi.org/10.1111/tpj.14500 failed (status code [40](https://github.com/soybase/jekyll-soybase/actions/runs/6039822999/job/16389397153#step:7:41)3)

**Comment by maxglycine** [comment]
I believe Steven said he would work on the Bandillo_Lorenz stuff. The DOI xx stuff I could not find and don't know why it was picked up. The 403 exit codes do work if you click on them so it might have been a lock out for too many hits a second.

**Comment by maxglycine** [comment]
There is still a pull request open from me for the changes I made.  It has not been pulled in.  I do not know if anyone has "looked at and OKed" the pull.

**Comment by StevenCannon-USDA** [comment]
@maxglycine Looks good. I've reviewed, approved, and merged it; then deleted the branch since the changes are in main now. I'll re-link the page from about/index.html this evening or tomorrow.

**Comment by StevenCannon-USDA** [comment]
I think I have fixed the remaining broken links. See https://github.com/soybase/jekyll-soybase/pull/24

**Comment by jd-campbell** [comment]
Done.
