### ISSUE TITLE
Gene search has unalterable drop boxes

### ISSUE THREAD

**Issue by maxglycine** [soybase/jekyll-soybase#31]
The gene search displays dropdown boxes that can not be changed.  (species, strains) They should simply not appear on the form.  Why show the user stuff they can not change?

**Comment by StevenCannon-USDA** [comment]
Species and strain can be set once genus is set. This has been the design from the start.

The change planned for this web component has been waiting on some updates from Alan. That will allow pre-setting the genus to Glycine. At that point, species should always be selectable. Strain will be selectable once species is selected.
