### ISSUE TITLE
Jekyll page:  Collection descriptions need to be augmented

### ISSUE THREAD

**Issue by jd-campbell** [soybase/jekyll-soybase#61]

**Comment by jd-campbell** [comment]
@maxglycine You created this task in September. What do you mean by this title? I need more info to determine what you want.

**Comment by maxglycine** [comment]
@jd-campbell The diversity section of the "Collections" page (dev.soybase.org/collections) really needs some more information.  If I was asking the question "which one of these studies(collections) used ZH13", I would have to click on the collection link of each and every collection, try and get each paper, then go through the list of germplasm they used to see if they used ZH13. I think we need a page (or database table) that lists every germplasm used in each of the diversity entries if it is not specified in the title.  Even if we had a page that just listed the germplasm used in each "collection", the user could use the browser search function to find the name in the lists. The user would still have try and get the paper for any further details, but at least it limits the number of papers they would have to pull. Some of the lists will be long, so I don't know if a yaml file is the way to go. Maybe just a plain HTML page that we could add to each time we add a new diversity study. Why would someone ask the question?  It would be the only way they could amass a list of all the SNPs known for a germplasm.

**Comment by StevenCannon-USDA** [comment]
One way we could do this: add a file to each diversity collection that lists the accessions. Given that file, we could (I think) easily pull that information into a page, via the datastore-metadata - as we do for the collections and resources. It may also be possible to extract this information from the mines - which would mean that there should be a ready-made API already.

Testing ... here's a bit of code that extracts the accession list. The last awk statement is to avoid printing the initial VCF metadata column headers. (For production, it should be put into a script and run across all collections, etc.):
```
VCF_FILE=glyma.Wm82.gnm2.div.Song_Yan_2017.SNPdata.parents.vcf.gz

zcat $VCF_FILE | awk '$1~/^#/' | tail -1 | tr '\t' '\n' | 
  awk 'seen_fmt {print} $1~/FORMAT/ {seen_fmt++}'
Parent-IA3023
TN05-3027
4J105-3-4
5M20-2-5-2
CL0J095-4-6
CL0J173-6-8
HS6-3976
Prohio
...

```

**Comment by jd-campbell** [comment]
@jd-campbell Christmas break project

Look at README file and possibly add this to STAINS

**Comment by jd-campbell** [comment]
@StevenCannon-USDA: There is no STRAINS section in the README - but there is a genotype section. I will trying adding the list of accession to one README to see how it works out. I added the list to "Glycine/max/diversity/Wm82.gnm1.div.ContrerasSoto_Mora_2017". 

I am wondering if it might be better is the list of genotypes is printed in one line seperated by a comma or list the accessions in its own file.

**Comment by That-Thing** [comment]
Given how many genotypes there are, would a collapsible accordion be better for this?
Listing them all out separated by commas takes up a lot of space and doesn't look very readable.

**Comment by StevenCannon-USDA** [comment]
@That-Thing - you're free to come up with something that looks decent.
I think the largest number of accessions in one of these collections is about 20,000. That's a pretty pathological case that we might need to handle differently somehow.

**Comment by jd-campbell** [comment]
@That-Thing 
I am looking over old issues and tasks that are on my list. Was there anything else I need to do complete this task.  
I vaguely remember I was supposed to send you a list??? 

If you are available we can discuss during the GitHub meeting tomorrow.

**Comment by That-Thing** [comment]
I think this was discussed vaguely in an earlier meeting. Since the number of collections varies by a lot and there are some that have a very large amount, keeping them all in the same page wouldn't be a good idea. 

I will be at the meeting tomorrow so we can discuss it further then.

**Comment by jd-campbell** [comment]
The group decided to do this a different way.
