### ISSUE TITLE
Move documents on SoyBase Classic to annex

### ISSUE THREAD

**Issue by jd-campbell** [soybase/jekyll-soybase#68]
https://data.legumeinfo.org/annex/Glycine/max/

- Clean up file name to remove special characters 
- File type needs to changed / remove white space and line endings. 

**Need to go through folders and make sure all is copied and organized.**

**Comment by jd-campbell** [comment]
@jd-campbell  work on during Christmas break

**Comment by jd-campbell** [comment]
I have found a large amount of PDF, doc, docx, xls, xlsx, jpg, and tiff files.  I have sent emails and scheduled meetings to sort out what to do with these files.

**Comment by maxglycine** [comment]
I have not received any invitations yet


Sent from my iPhone

On Dec 27, 2023, at 5:55 PM, Jacqueline Campbell ***@***.***> wrote:

﻿

I have found a large amount of PDF, doc, docx, xls, xlsx, jpg, and tiff files. I have sent emails and scheduled meetings to sort out what to do with these files.

**Comment by jd-campbell** [comment]
Add affy soychip probe hits to annex
