### ISSUE TITLE
Funky wrapping in Jekyll-Banner 

### ISSUE THREAD

**Issue by StevenCannon-USDA** [soybase/jekyll-soybase#78]
At https://dev.soybase.org, nav items now show only in-line with the site title and subhead, with the nav items taking precedence over the title ... meaning that in a midsized browser window, the site title gets squeezed out of existence. 
In a narrower browser window, wrapping succeeds ... but only showing the last two nav items (NEWS and EVENTS).
I think this behavior showed up after the December theme refactoring. Probably need help from @alancleary on this.

**Comment by alancleary** [comment]
It looks like you aren't using an appropriate responsive width threshold for your menus, and the lower menu hasn't been updated to be consistent with the upper menu. See see `navbar-menu.html` and `navbar-lower-menu.html` in the [`_includes/` section](https://github.com/legumeinfo/jekyll-theme-legumeinfo#_includes) of the theme's readme for details.

**Comment by StevenCannon-USDA** [comment]
Thanks, @alancleary. You were right - and I've learned a bit more about the theme and nav items now. The behavior will be fixed with merge of #79. Closing.
