### ISSUE TITLE
Need to change font color for the tools menu on the left of home page

### ISSUE THREAD

**Issue by maxglycine** [soybase/jekyll-soybase#81]
Need to change the font color on the tools menu on the left of the home page to BLACK

**Comment by StevenCannon-USDA** [comment]
Personally, I like the current Tools sidebar font. I think it's legible, but it helps keep the visual focus on the central content in the page. But I also don't feel particularly strong about it. Just seems like a debatable change. Maybe add a label of "enhancement" and leave open for discussion for a while.

**Comment by StevenCannon-USDA** [comment]
Closing after changing font to the SoyBase dark-green link color.
