### ISSUE TITLE
Trait Association Search data connection

### ISSUE THREAD

**Issue by StevenCannon-USDA** [soybase/jekyll-soybase#82]
After merging #77 (Trait search), the GitHub hosted instance (dev.soybase.org) is giving "Failed to load data" at https://dev.soybase.org/tools/search/trait.html . When I serve the same branch "main" locally, I don't see the error; and the gene search component is fine (locally and at dev.soybase.org). 

I am guessing the problem has to do with the theme not being updated at the GitHub instance, but I don't know. Paging @That-Thing and @nathanweeks to help figure this out.

**Comment by nathanweeks** [comment]
Right, the _themes/jekyll-theme-legumeinfo submodule needs to be updated to point to the latest commit in the upstream repository, e.g.:
```
git submodule update --remote _themes/jekyll-theme-legumeinfo
git commit -m 'update theme submodule' _themes/jekyll-theme-legumeinfo
git push origin my-branch
... submit PR ...
```

**Comment by StevenCannon-USDA** [comment]
Thanks. That seemed to work fine. I'll try to be in the habit of checking this going forward.
